// ============================================================
// WURMKIEG - Weapon Definitions & Registry
// ============================================================
import { WeaponDef, WeaponType } from './types';

export const WEAPONS: Record<string, WeaponDef> = {
  rocketLauncher: {
    id: 'rocketLauncher',
    name: 'Raketenwerfer',
    type: WeaponType.PROJECTILE,
    icon: '🚀',
    damage: 50,
    radius: 60,
    range: 800,
    ammo: 3,
    cooldown: 0,
    windAffected: true,
    gravity: 0.08,
    speed: 12,
    bounces: 0,
    fuseTime: 0,
    description: 'Steuerbare Rakete mit großer Explosionskraft',
  },
  bazooka: {
    id: 'bazooka',
    name: 'Bazooka',
    type: WeaponType.PROJECTILE,
    icon: '💣',
    damage: 40,
    radius: 50,
    range: 600,
    ammo: 4,
    cooldown: 0,
    windAffected: true,
    gravity: 0.12,
    speed: 10,
    bounces: 1,
    fuseTime: 2.0,
    description: 'Standard-Panzerabwehrrakete mit Zeitzünder',
  },
  grenade: {
    id: 'grenade',
    name: 'Handgranate',
    type: WeaponType.PROJECTILE,
    icon: '💥',
    damage: 35,
    radius: 45,
    range: 400,
    ammo: 5,
    cooldown: 0,
    windAffected: true,
    gravity: 0.18,
    speed: 8,
    bounces: 3,
    fuseTime: 3.0,
    description: 'Springende Granate mit Verzögerungszünder',
  },
  clusterGrenade: {
    id: 'clusterGrenade',
    name: 'Splittergranate',
    type: WeaponType.PROJECTILE,
    icon: '🧨',
    damage: 20,
    radius: 30,
    range: 400,
    ammo: 2,
    cooldown: 0,
    windAffected: true,
    gravity: 0.15,
    speed: 9,
    bounces: 2,
    fuseTime: 2.5,
    description: 'Explodiert in 6 kleinere Granaten',
  },
  dynamite: {
    id: 'dynamite',
    name: 'Dynamit',
    type: WeaponType.PLACED,
    icon: '🧨',
    damage: 60,
    radius: 70,
    range: 50,
    ammo: 2,
    cooldown: 0,
    windAffected: false,
    gravity: 0.2,
    speed: 5,
    bounces: 1,
    fuseTime: 5.0,
    description: 'Platzierbare Ladung mit langem Zünder',
  },
  laser: {
    id: 'laser',
    name: 'Laserwaffe',
    type: WeaponType.BEAM,
    icon: '⚡',
    damage: 30,
    radius: 8,
    range: 500,
    ammo: 3,
    cooldown: 2,
    windAffected: false,
    gravity: 0,
    speed: 0,
    bounces: 0,
    fuseTime: 0,
    description: 'Sofortiger Energiestrahl, durchdringt leichte Deckung',
  },
  gatlingGun: {
    id: 'gatlingGun',
    name: 'Gatling Gun',
    type: WeaponType.PROJECTILE,
    icon: '🔫',
    damage: 8,
    radius: 5,
    range: 350,
    ammo: 30,
    cooldown: 0,
    windAffected: false,
    gravity: 0.04,
    speed: 15,
    bounces: 0,
    fuseTime: 0,
    description: 'Schnellfeuer mit 30 Schuss und leichtem Streuverhalten',
  },
  microwave: {
    id: 'microwave',
    name: 'Mikrowelle',
    type: WeaponType.BEAM,
    icon: '📡',
    damage: 5,
    radius: 25,
    range: 200,
    ammo: 100,
    cooldown: 0,
    windAffected: false,
    gravity: 0,
    speed: 0,
    bounces: 0,
    fuseTime: 0,
    description: 'Kontinuierlicher Hitzestrahl, Schaden über Zeit',
  },
  chainsaw: {
    id: 'chainsaw',
    name: 'Kettensäge',
    type: WeaponType.MELEE,
    icon: '🪚',
    damage: 80,
    radius: 20,
    range: 25,
    ammo: 1,
    cooldown: 0,
    windAffected: false,
    gravity: 0,
    speed: 0,
    bounces: 0,
    fuseTime: 0,
    description: 'Verheerender Nahkampfangriff. Risiko!',
  },
  shotgun: {
    id: 'shotgun',
    name: 'Schrotflinte',
    type: WeaponType.PROJECTILE,
    icon: '🎯',
    damage: 12,
    radius: 5,
    range: 200,
    ammo: 3,
    cooldown: 1,
    windAffected: false,
    gravity: 0.06,
    speed: 14,
    bounces: 0,
    fuseTime: 0,
    description: '8 Kugeln mit kurzem Wirkbereich',
  },
  sniper: {
    id: 'sniper',
    name: 'Scharfschütze',
    type: WeaponType.INSTANT,
    icon: '🎯',
    damage: 55,
    radius: 10,
    range: 1500,
    ammo: 2,
    cooldown: 3,
    windAffected: false,
    gravity: 0,
    speed: 0,
    bounces: 0,
    fuseTime: 0,
    description: 'Hohe Präzision, durchdringt mehrere Ziele',
  },
  mine: {
    id: 'mine',
    name: 'Mine',
    type: WeaponType.PLACED,
    icon: '💀',
    damage: 45,
    radius: 40,
    range: 30,
    ammo: 3,
    cooldown: 0,
    windAffected: false,
    gravity: 0.2,
    speed: 3,
    bounces: 0,
    fuseTime: 0,
    description: 'Platzierbare Annäherungsmine',
  },
  airstrike: {
    id: 'airstrike',
    name: 'Luftangriff',
    type: WeaponType.PROJECTILE,
    icon: '✈️',
    damage: 35,
    radius: 50,
    range: 100,
    ammo: 1,
    cooldown: 0,
    windAffected: true,
    gravity: 0.1,
    speed: 8,
    bounces: 0,
    fuseTime: 0,
    description: '5 Bomben aus der Luft auf Zielgebiet',
  },
  drill: {
    id: 'drill',
    name: 'Bohrer',
    type: WeaponType.PROJECTILE,
    icon: '🔩',
    damage: 15,
    radius: 20,
    range: 300,
    ammo: 2,
    cooldown: 0,
    windAffected: false,
    gravity: 0.15,
    speed: 6,
    bounces: 0,
    fuseTime: 3.0,
    description: 'Bohrt sich durch Terrain und explodiert',
  },
  teleporter: {
    id: 'teleporter',
    name: 'Teleporter',
    type: WeaponType.UTILITY,
    icon: '🌀',
    damage: 0,
    radius: 0,
    range: 0,
    ammo: 2,
    cooldown: 0,
    windAffected: false,
    gravity: 0,
    speed: 0,
    bounces: 0,
    fuseTime: 0,
    description: 'Teleportiert an eine zufällige Position',
  },
  shield: {
    id: 'shield',
    name: 'Schutzschild',
    type: WeaponType.UTILITY,
    icon: '🛡️',
    damage: 0,
    radius: 0,
    range: 0,
    ammo: 2,
    cooldown: 0,
    windAffected: false,
    gravity: 0,
    speed: 0,
    bounces: 0,
    fuseTime: 0,
    description: 'Reduziert eingehenden Schaden für 1 Runde um 50%',
  },
  flamethrower: {
    id: 'flamethrower',
    name: 'Flammenwerfer',
    type: WeaponType.BEAM,
    icon: '🔥',
    damage: 4,
    radius: 20,
    range: 150,
    ammo: 80,
    cooldown: 0,
    windAffected: false,
    gravity: -0.02,
    speed: 0,
    bounces: 0,
    fuseTime: 0,
    description: 'Feuerstrahl mit Flächenschaden und Brandeffekt',
  },
  emp: {
    id: 'emp',
    name: 'EMP-Schocker',
    type: WeaponType.PROJECTILE,
    icon: '⚡',
    damage: 10,
    radius: 35,
    range: 300,
    ammo: 3,
    cooldown: 0,
    windAffected: true,
    gravity: 0.1,
    speed: 9,
    bounces: 1,
    fuseTime: 0,
    description: 'Betäubt Gegner für 1 Runde',
  },
};

export function getWeaponDef(id: string): WeaponDef {
  const w = WEAPONS[id];
  if (!w) throw new Error(`Unknown weapon: ${id}`);
  return w;
}

export function getAllWeaponIds(): string[] {
  return Object.keys(WEAPONS);
}

export function getDefaultLoadout(): string[] {
  return [
    'rocketLauncher', 'bazooka', 'grenade', 'clusterGrenade',
    'dynamite', 'laser', 'gatlingGun', 'microwave',
    'chainsaw', 'shotgun', 'sniper', 'mine',
    'airstrike', 'drill', 'teleporter', 'shield',
    'flamethrower', 'emp',
  ];
}
